version: 2

jobs:
  build:
    working_directory: ~/recipe-spring

    docker: circleci/openjdk:8-jdk-stretch

    steps:
        - checkout

        - restore_cache:
            key: recipe-spring-{{ checksum "pom.xml" }}

        - run: mvn dependency:go-offline

        - save_cache:
            paths:
              - ~/.m2
            key: recipe-spring-{{ checksum "pom.xml" }}

        - run: mvn verify

        - store_test_results:
            path: target/surefire-reports

        - store_artifacts:
            path: target/recipe-spring-0.0.1-SNAPSHOT.jar